drop table if exists encuesta;
create table encuesta 
(
	id  int primary key auto_increment , 
	fecha date,
	no_aplicacion integer,
	nombre_profesional varchar (40),
	a1_nombre_ie varchar (40) ,
	a2_nombre_sede varchar (40) ,
	a3_nombre_docente varchar (20),
	a4_edad integer,
	a6_municipio varchar (40),
	a7_estado_civil  integer,
	b1_a_nivel varchar (40),
	b1_b_nom_titulo varchar (40),
	b1_c_nivel_post varchar (40),
	b2_exp_docencia integer,
	b3_exp_sede integer,
	b4_jornada integer,
	
	/** inicio tabla pregunta 12 **/
	b5_a_sociales boolean default '0',
	b5_a_grado0 integer default '0',
	b5_a_grado1 integer default '0',
	b5_a_nivel1 varchar (40) default '',
	b5_a_grado2 integer default '0',
	b5_a_nivel2 varchar (40) default '',
	b5_a_grado3 integer default '0',
	b5_a_nivel3 varchar (40) default '',
	b5_a_grado4 integer default '0',
	b5_a_nivel4 varchar (40) default '',
	b5_a_grado5 integer default '0',
	b5_a_nivel5 varchar (40) default '',
	b5_a_grado6 integer default '0',
	b5_a_nivel6 varchar (40) default '',
	b5_a_grado7 integer default '0',
	b5_a_nivel7 varchar (40) default '',
	b5_a_grado8 integer default '0',
	b5_a_nivel8 varchar (40) default '',
	b5_a_grado9 integer default '0',
	b5_a_nivel9 varchar (40) default '',
	b5_a_grado10 integer default '0',
	b5_a_nivel10 varchar (40) default '',
	b5_a_grado11 integer default '0',
	b5_a_nivel11 varchar (40) default '',


	
	
	
	b5_b_etica boolean default '0',
	b5_b_grado0 integer default '0',
	b5_b_grado1 integer default '0',
	b5_b_nivel1 varchar (40) default '',
	b5_b_grado2 integer default '0',
	b5_b_nivel2 varchar (40) default '',
	b5_b_grado3 integer default '0',
	b5_b_nivel3 varchar (40) default '',
	b5_b_grado4 integer default '0',
	b5_b_nivel4 varchar (40) default '',
	b5_b_grado5 integer default '0',
	b5_b_nivel5 varchar (40) default '',
	b5_b_grado6 integer default '0',
	b5_b_nivel6 varchar (40) default '',
	b5_b_grado7 integer default '0',
	b5_b_nivel7 varchar (40) default '',
	b5_b_grado8 integer default '0',
	b5_b_nivel8 varchar (40) default '',
	b5_b_grado9 integer default '0',
	b5_b_nivel9 varchar (40) default '',
	b5_b_grado10 integer default '0',
	b5_b_nivel10 varchar (40) default '',
	b5_b_grado11 integer default '0',
	b5_b_nivel11 varchar (40) default '',


	
	
	
	b5_c_ciencias boolean default '0',
	b5_c_grado0 integer default '0',
	b5_c_grado1 integer default '0',
	b5_c_nivel1 varchar (40) default '',
	b5_c_grado2 integer default '0',
	b5_c_nivel2 varchar (40) default '',
	b5_c_grado3 integer default '0',
	b5_c_nivel3 varchar (40) default '',
	b5_c_grado4 integer default '0',
	b5_c_nivel4 varchar (40) default '',
	b5_c_grado5 integer default '0',
	b5_c_nivel5 varchar (40) default '',
	b5_c_grado6 integer default '0',
	b5_c_nivel6 varchar (40) default '',
	b5_c_grado7 integer default '0',
	b5_c_nivel7 varchar (40) default '',
	b5_c_grado8 integer default '0',
	b5_c_nivel8 varchar (40) default '',
	b5_c_grado9 integer default '0',
	b5_c_nivel9 varchar (40) default '',
	b5_c_grado10 integer default '0',
	b5_c_nivel10 varchar (40) default '',
	b5_c_grado11 integer default '0',
	b5_c_nivel11 varchar (40) default '',


	
	
	
	b5_d_matematicas boolean default '0',
	b5_d_grado0 integer default '0',
	b5_d_grado1 integer default '0',
	b5_d_nivel1 varchar (40) default '',
	b5_d_grado2 integer default '0',
	b5_d_nivel2 varchar (40) default '',
	b5_d_grado3 integer default '0',
	b5_d_nivel3 varchar (40) default '',
	b5_d_grado4 integer default '0',
	b5_d_nivel4 varchar (40) default '',
	b5_d_grado5 integer default '0',
	b5_d_nivel5 varchar (40) default '',
	b5_d_grado6 integer default '0',
	b5_d_nivel6 varchar (40) default '',
	b5_d_grado7 integer default '0',
	b5_d_nivel7 varchar (40) default '',
	b5_d_grado8 integer default '0',
	b5_d_nivel8 varchar (40) default '',
	b5_d_grado9 integer default '0',
	b5_d_nivel9 varchar (40) default '',
	b5_d_grado10 integer default '0',
	b5_d_nivel10 varchar (40) default '',
	b5_d_grado11 integer default '0',
	b5_d_nivel11 varchar (40) default '',


	b5_e_tecnologia boolean default '0',
	b5_e_grado0 integer default '0',
	b5_e_grado1 integer default '0',
	b5_e_nivel1 varchar (40) default '',
	b5_e_grado2 integer default '0',
	b5_e_nivel2 varchar (40) default '',
	b5_e_grado3 integer default '0',
	b5_e_nivel3 varchar (40) default '',
	b5_e_grado4 integer default '0',
	b5_e_nivel4 varchar (40) default '',
	b5_e_grado5 integer default '0',
	b5_e_nivel5 varchar (40) default '',
	b5_e_grado6 integer default '0',
	b5_e_nivel6 varchar (40) default '',
	b5_e_grado7 integer default '0',
	b5_e_nivel7 varchar (40) default '',
	b5_e_grado8 integer default '0',
	b5_e_nivel8 varchar (40) default '',
	b5_e_grado9 integer default '0',
	b5_e_nivel9 varchar (40) default '',
	b5_e_grado10 integer default '0',
	b5_e_nivel10 varchar (40) default '',
	b5_e_grado11 integer default '0',
	b5_e_nivel11 varchar (40) default '',


	
	b5_f_fisica boolean default '0',
	b5_f_grado0 integer default '0',
	b5_f_grado1 integer default '0',
	b5_f_nivel1 varchar (40) default '',
	b5_f_grado2 integer default '0',
	b5_f_nivel2 varchar (40) default '',
	b5_f_grado3 integer default '0',
	b5_f_nivel3 varchar (40) default '',
	b5_f_grado4 integer default '0',
	b5_f_nivel4 varchar (40) default '',
	b5_f_grado5 integer default '0',
	b5_f_nivel5 varchar (40) default '',
	b5_f_grado6 integer default '0',
	b5_f_nivel6 varchar (40) default '',
	b5_f_grado7 integer default '0',
	b5_f_nivel7 varchar (40) default '',
	b5_f_grado8 integer default '0',
	b5_f_nivel8 varchar (40) default '',
	b5_f_grado9 integer default '0',
	b5_f_nivel9 varchar (40) default '',
	b5_f_grado10 integer default '0',
	b5_f_nivel10 varchar (40) default '',
	b5_f_grado11 integer default '0',
	b5_f_nivel11 varchar (40) default '',


	
	b5_g_quimica boolean default '0',
	b5_g_grado0 integer default '0',
	b5_g_grado1 integer default '0',
	b5_g_nivel1 varchar (40) default '',
	b5_g_grado2 integer default '0',
	b5_g_nivel2 varchar (40) default '',
	b5_g_grado3 integer default '0',
	b5_g_nivel3 varchar (40) default '',
	b5_g_grado4 integer default '0',
	b5_g_nivel4 varchar (40) default '',
	b5_g_grado5 integer default '0',
	b5_g_nivel5 varchar (40) default '',
	b5_g_grado6 integer default '0',
	b5_g_nivel6 varchar (40) default '',
	b5_g_grado7 integer default '0',
	b5_g_nivel7 varchar (40) default '',
	b5_g_grado8 integer default '0',
	b5_g_nivel8 varchar (40) default '',
	b5_g_grado9 integer default '0',
	b5_g_nivel9 varchar (40) default '',
	b5_g_grado10 integer default '0',
	b5_g_nivel10 varchar (40) default '',
	b5_g_grado11 integer default '0',
	b5_g_nivel11 varchar (40) default '',


	b5_h_lenguaje boolean default '0',
	b5_h_grado0 integer default '0',
	b5_h_grado1 integer default '0',
	b5_h_nivel1 varchar (40) default '',
	b5_h_grado2 integer default '0',
	b5_h_nivel2 varchar (40) default '',
	b5_h_grado3 integer default '0',
	b5_h_nivel3 varchar (40) default '',
	b5_h_grado4 integer default '0',
	b5_h_nivel4 varchar (40) default '',
	b5_h_grado5 integer default '0',
	b5_h_nivel5 varchar (40) default '',
	b5_h_grado6 integer default '0',
	b5_h_nivel6 varchar (40) default '',
	b5_h_grado7 integer default '0',
	b5_h_nivel7 varchar (40) default '',
	b5_h_grado8 integer default '0',
	b5_h_nivel8 varchar (40) default '',
	b5_h_grado9 integer default '0',
	b5_h_nivel9 varchar (40) default '',
	b5_h_grado10 integer default '0',
	b5_h_nivel10 varchar (40) default '',
	b5_h_grado11 integer default '0',
	b5_h_nivel11 varchar (40) default '',


	b5_i_seg_lengua boolean default '0',
	b5_i_grado0 integer default '0',
	b5_i_grado1 integer default '0',
	b5_i_nivel1 varchar (40) default '',
	b5_i_grado2 integer default '0',
	b5_i_nivel2 varchar (40) default '',
	b5_i_grado3 integer default '0',
	b5_i_nivel3 varchar (40) default '',
	b5_i_grado4 integer default '0',
	b5_i_nivel4 varchar (40) default '',
	b5_i_grado5 integer default '0',
	b5_i_nivel5 varchar (40) default '',
	b5_i_grado6 integer default '0',
	b5_i_nivel6 varchar (40) default '',
	b5_i_grado7 integer default '0',
	b5_i_nivel7 varchar (40) default '',
	b5_i_grado8 integer default '0',
	b5_i_nivel8 varchar (40) default '',
	b5_i_grado9 integer default '0',
	b5_i_nivel9 varchar (40) default '',
	b5_i_grado10 integer default '0',
	b5_i_nivel10 varchar (40) default '',
	b5_i_grado11 integer default '0',
	b5_i_nivel11 varchar (40) default '',


	
	
	b5_j_deportes boolean default '0',
	b5_j_grado0 integer default '0',
	b5_j_grado1 integer default '0',
	b5_j_nivel1 varchar (40) default '',
	b5_j_grado2 integer default '0',
	b5_j_nivel2 varchar (40) default '',
	b5_j_grado3 integer default '0',
	b5_j_nivel3 varchar (40) default '',
	b5_j_grado4 integer default '0',
	b5_j_nivel4 varchar (40) default '',
	b5_j_grado5 integer default '0',
	b5_j_nivel5 varchar (40) default '',
	b5_j_grado6 integer default '0',
	b5_j_nivel6 varchar (40) default '',
	b5_j_grado7 integer default '0',
	b5_j_nivel7 varchar (40) default '',
	b5_j_grado8 integer default '0',
	b5_j_nivel8 varchar (40) default '',
	b5_j_grado9 integer default '0',
	b5_j_nivel9 varchar (40) default '',
	b5_j_grado10 integer default '0',
	b5_j_nivel10 varchar (40) default '',
	b5_j_grado11 integer default '0',
	b5_j_nivel11 varchar (40) default '',


	b5_k_artes boolean default '0',
	b5_k_grado0 integer default '0',
	b5_k_grado1 integer default '0',
	b5_k_nivel1 varchar (40) default '',
	b5_k_grado2 integer default'0',
	b5_k_nivel2 varchar (40) default '',
	b5_k_grado3 integer default '0',
	b5_k_nivel3 varchar (40) default '',
	b5_k_grado4 integer default '0',
	b5_k_nivel4 varchar (40) default '',
	b5_k_grado5 integer default '0',
	b5_k_nivel5 varchar (40) default '',
	b5_k_grado6 integer default '0',
	b5_k_nivel6 varchar (40) default '',
	b5_k_grado7 integer default '0',
	b5_k_nivel7 varchar (40) default '',
	b5_k_grado8 integer default '0',
	b5_k_nivel8 varchar (40) default '',
	b5_k_grado9 integer default '0',
	b5_k_nivel9 varchar (40) default '',
	b5_k_grado10 integer default '0',
	b5_k_nivel10 varchar (40) default '',
	b5_k_grado11 integer default '0',
	b5_k_nivel11 varchar (40) default '',


	b5_l_religion boolean default '0',
	b5_l_grado0 integer default '0',
	b5_l_grado1 integer default '0',
	b5_l_nivel1 varchar (40) default '',
	b5_l_grado2 integer default '0',
	b5_l_nivel2 varchar (40) default '',
	b5_l_grado3 integer default '0',
	b5_l_nivel3 varchar (40) default '',
	b5_l_grado4 integer default '0',
	b5_l_nivel4 varchar (40) default '',
	b5_l_grado5 integer default '0',
	b5_l_nivel5 varchar (40) default '',
	b5_l_grado6 integer default '0',
	b5_l_nivel6 varchar (40) default '',
	b5_l_grado7 integer default '0',
	b5_l_nivel7 varchar (40) default '',
	b5_l_grado8 integer default '0',
	b5_l_nivel8 varchar (40) default '',
	b5_l_grado9 integer default '0',
	b5_l_nivel9 varchar (40) default '',
	b5_l_grado10 integer default '0',
	b5_l_nivel10 varchar (40) default '',
	b5_l_grado11 integer default '0',
	b5_l_nivel11 varchar (40) default '',
	
	
	b5_m_escuela_nueva boolean default '0',
	b5_m_grado0 integer default '0',
	b5_m_grado1 integer default '0',
	b5_m_nivel1 varchar (40) default '',
	b5_m_grado2 integer default '0',
	b5_m_nivel2 varchar (40) default '',
	b5_m_grado3 integer default '0',
	b5_m_nivel3 varchar (40) default '',
	b5_m_grado4 integer default '0',
	b5_m_nivel4 varchar (40) default '',
	b5_m_grado5 integer default '0',
	b5_m_nivel5 varchar (40) default '',
	b5_m_grado6 integer default '0',
	b5_m_nivel6 varchar (40) default '',
	b5_m_grado7 integer default '0',
	b5_m_nivel7 varchar (40) default '',
	b5_m_grado8 integer default '0',
	b5_m_nivel8 varchar (40) default '',
	b5_m_grado9 integer default '0',
	b5_m_nivel9 varchar (40) default '',
	b5_m_grado10 integer default '0',
	b5_m_nivel10 varchar (40) default '',
	b5_m_grado11 integer default '0',
	b5_m_nivel11 varchar (40) default '',


	
	
	b5_n_otra_asig1 varchar (20) default '',
	b5_n_grado0 integer default '0',
	b5_n_grado1 integer default '0',
	b5_n_nivel1 varchar (40) default '',
	b5_n_grado2 integer default '0',
	b5_n_nivel2 varchar (40) default '',
	b5_n_grado3 integer default '0',
	b5_n_nivel3 varchar (40) default '',
	b5_n_grado4 integer default '0',
	b5_n_nivel4 varchar (40) default '',
	b5_n_grado5 integer default '0',
	b5_n_nivel5 varchar (40) default '',
	b5_n_grado6 integer default '0',
	b5_n_nivel6 varchar (40) default '',
	b5_n_grado7 integer default '0',
	b5_n_nivel7 varchar (40) default '',
	b5_n_grado8 integer default '0',
	b5_n_nivel8 varchar (40) default '',
	b5_n_grado9 integer default '0',
	b5_n_nivel9 varchar (40) default '',
	b5_n_grado10 integer default '0',
	b5_n_nivel10 varchar (40) default '',
	b5_n_grado11 integer default '0',
	b5_n_nivel11 varchar (40) default '',


	
	
	b5_o_otra_asig2 varchar (20) default '',
	b5_o_grado0 integer default '0',
	b5_o_grado1 integer default '0',
	b5_o_nivel1 varchar (40) default '',
	b5_o_grado2 integer default '0',
	b5_o_nivel2 varchar (40) default '',
	b5_o_grado3 integer default '0',
	b5_o_nivel3 varchar (40) default '',
	b5_o_grado4 integer default '0',
	b5_o_nivel4 varchar (40) default '',
	b5_o_grado5 integer default '0',
	b5_o_nivel5 varchar (40) default '',
	b5_o_grado6 integer default '0',
	b5_o_nivel6 varchar (40) default '',
	b5_o_grado7 integer default '0',
	b5_o_nivel7 varchar (40) default '',
	b5_o_grado8 integer default '0',
	b5_o_nivel8 varchar (40) default '',
	b5_o_grado9 integer default '0',
	b5_o_nivel9 varchar (40) default '',
	b5_o_grado10 integer default '0',
	b5_o_nivel10 varchar (40) default '',
	b5_o_grado11 integer default '0',
	b5_o_nivel11 varchar (40) default '',

	/** fin tabla pregunta 12 **/
	/** inicio tabla pregunta 13 **/
	c1_a_convivencia boolean default '0',
	c1_a_duracion integer,
	c1_a_finalizo integer,
	
	c1_b_derechos boolean default '0',
	c1_b_duracion integer,
	c1_b_finalizo integer,
	
	c1_c_sexualidad boolean default '0',
	c1_c_duracion integer,
	c1_c_finalizo integer,
	
	c1_d_ambiente boolean default '0',
	c1_d_duracion integer,
	c1_d_finalizo integer,
	
	c1_e_prevencion boolean default '0',
	c1_e_duracion integer,
	c1_e_finalizo integer,
	
	c1_f_mediacion boolean default '0',
	c1_f_duracion integer,
	c1_f_finalizo integer,
	
	c1_g_acoso boolean default '0',
	c1_g_duracion integer,
	c1_g_finalizo integer,
	
	/** fin tabla pregunta 13 **/
	
	/** inicio tabla pregunta 15 **/
	c2_a_normas boolean default '0',
	c2_a_frecuencia integer default '0',
	
	c2_b_fort_valores boolean default '0',	
	c2_b_frecuencia integer default '0',	
	
	c2_c_cono_vida boolean default '0',	
	c2_c_frecuencia integer default '0',
		
	c2_d_cono_problemas boolean default '0',	
	c2_d_frecuencia integer default '0',	
	
	c2_e_autoestima boolean default '0',	
	c2_e_frecuencia integer default '0',
		
	c2_f_trab_equipo boolean default '0',	
	c2_f_frecuencia integer default '0',
	
	c2_g_pausa_activa boolean default '0',	
	c2_g_frecuencia integer default '0',
	
	c2_h_juegos boolean default '0',	
	c2_h_frecuencia integer default '0',
	
	c2_i_asamblea boolean default '0',	
	c2_i_frecuencia integer default '0',
	
	c2_j_otro1 boolean default '0',
	c2_j_otro1_nombre varchar (40),
	c2_j_frecuencia integer default '0',
	
	c2_k_otro2 boolean default '0',	
	c2_k_otro2_nombre varchar (40),
	c2_k_frecuencia integer default '0',
	/** fin tabla pregunta 15 **/
	/** inicio tabla pregunta 16 **/ 
	c3_exposicion integer,
	c3_debate integer,
	c3_mesa_redonda integer,
	c3_foro integer,
	c3_juego integer,
	c3_asamblea integer,
	c3_estrategia_ondas integer,
	c3_proyecto_aula integer,
	c3_expo_problema integer,
	c3_jornada_seguimiento integer,
	c3_monitor integer,
	/** fin tabla pregunta 16 **/ 
	
	/** inicio tabla pregunta 17 **/
	c4_separar_pelea integer,
	c4_dialogo integer,
	c4_trab_escrito integer,
	c4_ayuda integer,
	c4_acuerdo integer,
	c4_sanciones integer,
	c4_mediadores integer,
	c4_anotar_observaciones integer,
	c4_redes_apoyo integer,
	c4_reunion integer,
	c4_citacion integer,
	/** fin tabla pregunta 17 **/
	
	c5_aplica integer,
	c5_aplicacion text,
	
	created_at timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	updated_at timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'	
);
